import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../component/Navbar";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";
import { PageThemeProvider } from "@/lib/PageThemeProvider";
import Donate from "@/component/Donate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DOHPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <ThemeProvider>
          <PageThemeProvider>
            <Navbar />
            {children}
            <Donate />
          </PageThemeProvider>
        </ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
